#image
FROM bitnami/postgresql:latest

ENV POSTGRESQL_username=postgres
ENV POSTGRESQL_PASSWORD=root
ENV POSTGRESQL_DATABASE=rembirthday-db

VOLUME [ "/home/legolaz/projects/rembirthday/db", "/bitnami/postgresql" ]

EXPOSE 5432